### ISSUE TITLE
Arguments problem

### ISSUE THREAD

**Issue by Myztic90** [jcageman/d2mapapi#10]
These arguments dosent work. If i type any of below examples it will fail, if i dont use arguments it will work.

tried many diffrent ways like 

d2mapapi.exe "pathtomydiablo2"   this will work but dosent have arguments, but the rest i try to change port.

d2mapapi.exe "pathtomydiablo2" "-p 1234"           not working
d2mapapi.exe "pathtomydiablo2" `-p 1234`            not working
d2mapapi.exe "pathtomydiablo2" -p 12342            not working
d2mapapi.exe "pathtomydiablo2" `--port=8080`    not working
d2mapapi.exe "pathtomydiablo2" "--port=8080"   not working
d2mapapi.exe "pathtomydiablo2" --port=8080      not working

**Comment by jcageman** [comment]
Did you build from source or did you download the latest release binary?

**Comment by Myztic90** [comment]
I think i tried both. I can try again which one should I try???

Mvh Elvir

Den mån 29 nov. 2021 21:43jcageman ***@***.***> skrev:

**Comment by jcageman** [comment]
I've created a new binary release which should support the new arguments.

https://github.com/jcageman/d2mapapi/releases/tag/1.1

Examples how to run:
https://github.com/jcageman/d2mapapi#examples

I am using windows and have the following powershell script to run it locally:
Start-Process -FilePath "C:\Windows\System32\cmd.exe" -WorkingDirectory "C:\Users\myuser\Documents\GitHub\d2mapapi\Release" -verb runas -ArgumentList {/k d2mapapi.exe "C:\Diablo II" --port=7000}

**Comment by Myztic90** [comment]
works now :) thanks
