### ISSUE TITLE
Player unit not found

### ISSUE THREAD

**Issue by dawoat** [jcageman/d2mapapi#11]
Hello everybody.
Till the patch today. You get the error Player unit not found.

Could you investigate this Problem.

Thx

**Comment by scizzydo** [comment]
That has absolutely nothing to do with this project :)

**Comment by dawoat** [comment]
ok. after updating the uisettings and unithashtable. you get the error mapseed out of bounds.

**Comment by RushTheOne** [comment]
1.13c got a patch today? :O
