### ISSUE TITLE
Make it work for diablo 2 resurrected

### ISSUE THREAD

**Issue by jinincarnate** [jcageman/d2mapapi#17]
![image](https://user-images.githubusercontent.com/9129660/219946216-9b458c10-9097-42ad-8bce-6c8f035784a3.png)

Can u help with this issue, I m trying to generate map for diablo 2 resurrected

**Comment by jcageman** [comment]
This tool only supports old diablo. for resurrected look at for example:
https://github.com/blacha/diablo2
https://github.com/soarqin/D2RMH
