### ISSUE TITLE
Exception Unhandled: System.AccessViolationException

### ISSUE THREAD

**Issue by dmwm1024** [jcageman/d2mapapi#18]
Error received upon receiving any GET request.

System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

Encountered via the release version as well as the self compile (with launchSettings configured).

Call Stack:
 	[External Code]	
>	D2Map.Core.dll!D2Map.Core.Models.Session.GetMap(D2Map.Core.Models.Area area) Line 28	C#
 	D2Map.Core.dll!D2Map.Core.MapService.GetCollisionMap(uint mapId, D2Map.Core.Models.Difficulty difficulty, D2Map.Core.Models.Area area) Line 25	C#
 	D2Map.Api.dll!D2Map.Api.Controllers.MapApiController.Get(D2Map.Api.Controllers.Models.MapParameters parameters) Line 21	C#
 	[External Code]

**Comment by jcageman** [comment]
Which version of diablo 2 are you running? Highly likely not 1.13c or a modded version of it?

**Comment by dmwm1024** [comment]
I'm a dummy. Wrong version. Thank you for your time!

**Comment by dmwm1024** [comment]
Are there an examples of how to visualize the output?

**Comment by jcageman** [comment]
Nope, didn't make anything for that yet, you can look at [my diablo 1.09 bot](https://github.com/jcageman/Diablo2Clientless1.09) to see how i use the API output though
