### ISSUE TITLE
Compiling under Linux?

### ISSUE THREAD

**Issue by RulerOf** [jcageman/d2mapapi#6]
Hi,

I was trying to compile this app on Linux but ended up hitting walls where it complains about not being able to find `windows.h`. I tried with `dotnet build` and also with `msbuild` but didn't have much success.

It's not immediately clear to me if this app can be compiled directly for Linux but with it working so well under Wine, I wouldn't mind cross-compiling it—I'm just really confused by what I'd need to actually make that work.

The goal here is to build it in Docker.

**Comment by jcageman** [comment]
The windows.h dependency indicates it can only be build on Windows. I would be willing to accept PR's for linux, but not sure what would be needed to get it working there. The current code does dll loading which is windows specific, hence that makes it hard to cross compile it. For linux you need a different mechanism to load the files, which will probably make it quite different.

**Comment by RulerOf** [comment]
@jcageman I containerized the binary build of the application using the s6 overlay with a service health check, as I was having a lot of problems with this crashing on me: https://github.com/RulerOf/d2mapapi-docker

If it's at all possible to get this cross-compiled under Linux, or even just windows-based CI on this repo, that would probably be enough to warrant a PR that merges the assets into this repo.
